#!/bin/sh
ftp 112.213.89.59 << ftpEOF
prompt

quote pasv
binary
cd "/www"
lcd temp
mput "index.html"

mkdir images
cd images
mkdir fancybox
cd fancybox
lcd images
lcd fancybox
mput *.gif
mput *.png
cd /www
lcd ..
lcd ..

mkdir bat
cd bat
mput bat/MailHandler.php
cd /www

mkdir styles
cd styles
mput styles/*.main.css
mkdir images
cd images
mput styles/images/*.png
cd /www

mkdir views
cd views
mput views/*.html
cd ..

mkdir scripts
cd scripts
mput scripts/*.scripts.js
cd ..

close
quit
